const CuttingPlan = {
  order_id: 8,
  group_id: 'G-E4CE932B',
  bbLossRate: 13.7,
  cbLossRate: 42.6,
  bbCode: 'I38*5*3_1100',
  bbUsage: 498.7,
  cbUsage: 26,
  bbLoss: 68.1,
  cbCode: 'F25*4.5*1.2_6100',
  cbLoss: 42.5,
  result: {
    table: [
      {
        panelNumber: 1,
        qty: 1,
        gratings: 4,
        loss: 24,
        gratings_data: [
          {
            id: '15',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 985,
            lep_mm: 43,
            rep_mm: 43,
            leftCut: 15,
            rightCut: 1001,
            leftWeld: 58,
            rightWeld: 958,
            item_qty: 1,
          },
          {
            id: '26',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 1001,
            rightCut: 2871,
            leftWeld: 1086,
            rightWeld: 2786,
            item_qty: 3,
          },
          {
            id: '26',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 2871,
            rightCut: 4741,
            leftWeld: 2956,
            rightWeld: 4656,
            item_qty: 3,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 4741,
            rightCut: 6091,
            leftWeld: 4816,
            rightWeld: 6116,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 2,
        qty: 1,
        gratings: 4,
        loss: 24,
        gratings_data: [
          {
            id: '25',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 15,
            rightCut: 1885,
            leftWeld: 100,
            rightWeld: 1800,
            item_qty: 1,
          },
          {
            id: '19',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 985,
            lep_mm: 43,
            rep_mm: 43,
            leftCut: 1885,
            rightCut: 2871,
            leftWeld: 1928,
            rightWeld: 2828,
            item_qty: 1,
          },
          {
            id: '24',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 2871,
            rightCut: 4741,
            leftWeld: 2956,
            rightWeld: 4656,
            item_qty: 1,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 4741,
            rightCut: 6091,
            leftWeld: 4816,
            rightWeld: 6116,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 3,
        qty: 1,
        gratings: 4,
        loss: 46,
        gratings_data: [
          {
            id: '14',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 15,
            rightCut: 1805,
            leftWeld: 60,
            rightWeld: 1760,
            item_qty: 1,
          },
          {
            id: '18',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1805,
            rightCut: 3595,
            leftWeld: 1850,
            rightWeld: 3550,
            item_qty: 1,
          },
          {
            id: '11',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 3595,
            rightCut: 4879,
            leftWeld: 3687,
            rightWeld: 4787,
            item_qty: 1,
          },
          {
            id: '8',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4879,
            rightCut: 6069,
            leftWeld: 4924,
            rightWeld: 6024,
            item_qty: 1,
          },
        ],
      },
      {
        panelNumber: 4,
        qty: 1,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '4',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 1,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 31,
          },
        ],
      },
      {
        panelNumber: 5,
        qty: 1,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '1',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 1,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 31,
          },
        ],
      },
      {
        panelNumber: 6,
        qty: 1,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '3',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 1,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 31,
          },
        ],
      },
      {
        panelNumber: 7,
        qty: 4,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '2',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 6,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 31,
          },
        ],
      },
      {
        panelNumber: 11,
        qty: 1,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '2',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 6,
          },
          {
            id: '10',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 1,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 31,
          },
          {
            id: '6',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 31,
          },
        ],
      },
      {
        panelNumber: 12,
        qty: 1,
        gratings: 4,
        loss: 86,
        gratings_data: [
          {
            id: '29',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 65,
            rightCut: 1835,
            leftWeld: 50,
            rightWeld: 1750,
            item_qty: 10,
          },
          {
            id: '2',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 1835,
            rightCut: 3119,
            leftWeld: 1927,
            rightWeld: 3027,
            item_qty: 6,
          },
          {
            id: '9',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3119,
            rightCut: 4309,
            leftWeld: 3164,
            rightWeld: 4264,
            item_qty: 1,
          },
          {
            id: '29',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 4309,
            rightCut: 6079,
            leftWeld: 4394,
            rightWeld: 6094,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 13,
        qty: 1,
        gratings: 4,
        loss: 180,
        gratings_data: [
          {
            id: '26',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 15,
            rightCut: 1885,
            leftWeld: 100,
            rightWeld: 1800,
            item_qty: 3,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 1885,
            rightCut: 3235,
            leftWeld: 1960,
            rightWeld: 3260,
            item_qty: 10,
          },
          {
            id: '28',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 3325,
            rightCut: 4675,
            leftWeld: 3300,
            rightWeld: 4600,
            item_qty: 10,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 4675,
            rightCut: 6025,
            leftWeld: 4750,
            rightWeld: 6050,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 14,
        qty: 1,
        gratings: 4,
        loss: 280,
        gratings_data: [
          {
            id: '29',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 65,
            rightCut: 1835,
            leftWeld: 50,
            rightWeld: 1750,
            item_qty: 10,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 1835,
            rightCut: 3185,
            leftWeld: 1910,
            rightWeld: 3210,
            item_qty: 10,
          },
          {
            id: '28',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 3275,
            rightCut: 4625,
            leftWeld: 3250,
            rightWeld: 4550,
            item_qty: 10,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 4625,
            rightCut: 5975,
            leftWeld: 4700,
            rightWeld: 6000,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 15,
        qty: 2,
        gratings: 3,
        loss: 790,
        gratings_data: [
          {
            id: '29',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 15,
            rightCut: 1785,
            leftWeld: 100,
            rightWeld: 1800,
            item_qty: 10,
          },
          {
            id: '29',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 1855,
            rightCut: 3625,
            leftWeld: 1840,
            rightWeld: 3540,
            item_qty: 10,
          },
          {
            id: '29',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 3625,
            rightCut: 5395,
            leftWeld: 3710,
            rightWeld: 5410,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 17,
        qty: 1,
        gratings: 5,
        loss: 56,
        gratings_data: [
          {
            id: '5',
            option: 0,
            width_mm: 755,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1283,
            lep_mm: 92,
            rep_mm: 92,
            leftCut: 15,
            rightCut: 1299,
            leftWeld: 107,
            rightWeld: 1207,
            item_qty: 1,
          },
          {
            id: '7',
            option: 0,
            width_mm: 755,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1299,
            rightCut: 2489,
            leftWeld: 1344,
            rightWeld: 2444,
            item_qty: 4,
          },
          {
            id: '7',
            option: 0,
            width_mm: 755,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2489,
            rightCut: 3679,
            leftWeld: 2534,
            rightWeld: 3634,
            item_qty: 4,
          },
          {
            id: '7',
            option: 0,
            width_mm: 755,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3679,
            rightCut: 4869,
            leftWeld: 3724,
            rightWeld: 4824,
            item_qty: 4,
          },
          {
            id: '7',
            option: 0,
            width_mm: 755,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4869,
            rightCut: 6059,
            leftWeld: 4914,
            rightWeld: 6014,
            item_qty: 4,
          },
        ],
      },
      {
        panelNumber: 18,
        qty: 1,
        gratings: 3,
        loss: 1110,
        gratings_data: [
          {
            id: '28',
            option: 2,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 75,
            rightCut: 1425,
            leftWeld: 50,
            rightWeld: 1350,
            item_qty: 10,
          },
          {
            id: '23',
            option: 0,
            width_mm: 665,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 1425,
            rightCut: 3295,
            leftWeld: 1510,
            rightWeld: 3210,
            item_qty: 1,
          },
          {
            id: '29',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1770,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 3295,
            rightCut: 5065,
            leftWeld: 3380,
            rightWeld: 5080,
            item_qty: 10,
          },
        ],
      },
      {
        panelNumber: 19,
        qty: 1,
        gratings: 4,
        loss: 140,
        gratings_data: [
          {
            id: '17',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 15,
            rightCut: 1805,
            leftWeld: 60,
            rightWeld: 1760,
            item_qty: 2,
          },
          {
            id: '17',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1805,
            rightCut: 3595,
            leftWeld: 1850,
            rightWeld: 3550,
            item_qty: 2,
          },
          {
            id: '13',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3595,
            rightCut: 4785,
            leftWeld: 3640,
            rightWeld: 4740,
            item_qty: 1,
          },
          {
            id: '21',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4785,
            rightCut: 5975,
            leftWeld: 4830,
            rightWeld: 5930,
            item_qty: 1,
          },
        ],
      },
      {
        panelNumber: 20,
        qty: 1,
        gratings: 4,
        loss: 140,
        gratings_data: [
          {
            id: '20',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 15,
            rightCut: 1805,
            leftWeld: 60,
            rightWeld: 1760,
            item_qty: 1,
          },
          {
            id: '16',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1790,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 1805,
            rightCut: 3595,
            leftWeld: 1850,
            rightWeld: 3550,
            item_qty: 1,
          },
          {
            id: '22',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3595,
            rightCut: 4785,
            leftWeld: 3640,
            rightWeld: 4740,
            item_qty: 1,
          },
          {
            id: '12',
            option: 0,
            width_mm: 635,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1190,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4785,
            rightCut: 5975,
            leftWeld: 4830,
            rightWeld: 5930,
            item_qty: 1,
          },
        ],
      },
      {
        panelNumber: 21,
        qty: 1,
        gratings: 2,
        loss: 2880,
        gratings_data: [
          {
            id: '27',
            option: 0,
            width_mm: 455,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1870,
            lep_mm: 85,
            rep_mm: 85,
            leftCut: 15,
            rightCut: 1885,
            leftWeld: 100,
            rightWeld: 1800,
            item_qty: 1,
          },
          {
            id: '28',
            option: 0,
            width_mm: 995,
            orderNumber: 'KP2403-007A',
            customerCode: '영빈테크',
            drawingNumber: 'P01',
            length_mm: 1350,
            lep_mm: 75,
            rep_mm: 75,
            leftCut: 1885,
            rightCut: 3235,
            leftWeld: 1960,
            rightWeld: 3260,
            item_qty: 10,
          },
        ],
      },
    ],
  },
};
export default CuttingPlan;
