const CuttingPlan = {
  order_id: 8,
  group_id: 'G-E4CE932B',
  bbLossRate: 13.7,
  cbLossRate: 42.6,
  bbCode: 'I38*5*3_1100',
  bbUsage: 498.7,
  cbUsage: 26,
  bbLoss: 68.1,
  cbCode: 'F25*4.5*1.2_6100',
  cbLoss: 42.5,
  result: {
    table: [
      {
        panelNumber: 1,
        qty: 1,
        gratings: 5,
        loss: 5.4,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-12',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1410,
            rightCut: 2590,
            leftWeld: 1450,
            rightWeld: 2550,
            item_qty: 3,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2004-06',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1080,
            lep_mm: 90,
            rep_mm: 90,
            leftCut: 4950,
            rightCut: 6030,
            leftWeld: 5040,
            rightWeld: 5940,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 2,
        qty: 1,
        gratings: 5,
        loss: 5.4,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-16',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1410,
            rightCut: 2590,
            leftWeld: 1450,
            rightWeld: 2550,
            item_qty: 3,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2004-10',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1080,
            lep_mm: 90,
            rep_mm: 90,
            leftCut: 4950,
            rightCut: 6030,
            leftWeld: 5040,
            rightWeld: 5940,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 3,
        qty: 1,
        gratings: 5,
        loss: 8.8,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-18',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1410,
            rightCut: 2590,
            leftWeld: 1450,
            rightWeld: 2550,
            item_qty: 3,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2002-18',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 4950,
            rightCut: 5930,
            leftWeld: 4990,
            rightWeld: 5890,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 4,
        qty: 1,
        gratings: 5,
        loss: 8.8,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-32',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1410,
            rightCut: 2590,
            leftWeld: 1450,
            rightWeld: 2550,
            item_qty: 3,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2002-18',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 4950,
            rightCut: 5930,
            leftWeld: 4990,
            rightWeld: 5890,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 5,
        qty: 1,
        gratings: 5,
        loss: 8.8,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 2,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2006-15',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 2790,
            rightCut: 3970,
            leftWeld: 2830,
            rightWeld: 3930,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2004-24',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 3970,
            rightCut: 4950,
            leftWeld: 4010,
            rightWeld: 4910,
            item_qty: 2,
            lCuttingNumber: 4,
          },
        ],
      },
      {
        panelNumber: 6,
        qty: 1,
        gratings: 5,
        loss: 10.9,
        gratings_data: [
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1410,
            leftWeld: 70,
            rightWeld: 1370,
            item_qty: 2,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2002-08',
            option: 0,
            width_mm: 635,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 2790,
            rightCut: 3770,
            leftWeld: 2830,
            rightWeld: 3730,
            item_qty: 2,
            lCuttingNumber: 7,
          },
          {
            id: 'GR2002-13',
            option: 0,
            width_mm: 335,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 2790,
            rightCut: 3770,
            leftWeld: 2830,
            rightWeld: 3730,
            item_qty: 2,
            lCuttingNumber: 7,
          },
          {
            id: 'GR2006-04',
            option: 0,
            width_mm: 965,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 4750,
            rightCut: 5930,
            leftWeld: 4790,
            rightWeld: 5890,
            item_qty: 1,
            lCuttingNumber: 7,
          },
        ],
      },
      {
        panelNumber: 7,
        qty: 1,
        gratings: 5,
        loss: 10.9,
        gratings_data: [
          {
            id: 'GR2004-13',
            option: 0,
            width_mm: 395,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2004-21',
            option: 0,
            width_mm: 575,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2002-07',
            option: 0,
            width_mm: 665,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 1990,
            leftWeld: 1050,
            rightWeld: 1950,
            item_qty: 1,
            lCuttingNumber: 5,
          },
          {
            id: 'GR2004-07',
            option: 0,
            width_mm: 305,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 1990,
            leftWeld: 1050,
            rightWeld: 1950,
            item_qty: 1,
            lCuttingNumber: 5,
          },
          {
            id: 'GR2002-01',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1990,
            rightCut: 3370,
            leftWeld: 2030,
            rightWeld: 3330,
            item_qty: 2,
            lCuttingNumber: 5,
          },
          {
            id: 'GR2006-12',
            option: 0,
            width_mm: 965,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 4750,
            rightCut: 5930,
            leftWeld: 4790,
            rightWeld: 5890,
            item_qty: 1,
            lCuttingNumber: 7,
          },
        ],
      },
      {
        panelNumber: 8,
        qty: 1,
        gratings: 5,
        loss: 20.7,
        gratings_data: [
          {
            id: 'GR2002-12',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2004-19',
            option: 0,
            width_mm: 245,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2002-02',
            option: 0,
            width_mm: 995,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 2390,
            leftWeld: 1050,
            rightWeld: 2350,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2002-01B',
            option: 0,
            width_mm: 965,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1380,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 2390,
            rightCut: 3770,
            leftWeld: 2430,
            rightWeld: 3730,
            item_qty: 1,
            lCuttingNumber: 4,
          },
          {
            id: 'GR2004-03',
            option: 0,
            width_mm: 545,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 3770,
            rightCut: 4750,
            leftWeld: 3810,
            rightWeld: 4710,
            item_qty: 2,
            lCuttingNumber: 9,
          },
          {
            id: 'GR2004-27',
            option: 0,
            width_mm: 395,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 3770,
            rightCut: 4750,
            leftWeld: 3810,
            rightWeld: 4710,
            item_qty: 2,
            lCuttingNumber: 9,
          },
        ],
      },
      {
        panelNumber: 9,
        qty: 1,
        gratings: 5,
        loss: 47.8,
        gratings_data: [
          {
            id: 'GR2004-14',
            option: 0,
            width_mm: 965,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 3,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2006-05',
            option: 0,
            width_mm: 815,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1243,
            lep_mm: 72,
            rep_mm: 72,
            leftCut: 2970,
            rightCut: 4214,
            leftWeld: 3042,
            rightWeld: 4142,
            item_qty: 2,
            lCuttingNumber: 4,
          },
        ],
      },
      {
        panelNumber: 10,
        qty: 1,
        gratings: 5,
        loss: 42.5,
        gratings_data: [
          {
            id: 'GR2004-28',
            option: 0,
            width_mm: 965,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 2,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2005-01',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1410,
            lep_mm: 55,
            rep_mm: 55,
            leftCut: 1990,
            rightCut: 3400,
            leftWeld: 2045,
            rightWeld: 3345,
            item_qty: 2,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2002-10',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1290,
            lep_mm: 95,
            rep_mm: 95,
            leftCut: 4810,
            rightCut: 6100,
            leftWeld: 4905,
            rightWeld: 6005,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 11,
        qty: 1,
        gratings: 5,
        loss: 54.2,
        gratings_data: [
          {
            id: 'GR2005-07',
            option: 0,
            width_mm: 905,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 2,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2005-02',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1304,
            lep_mm: 52,
            rep_mm: 52,
            leftCut: 1990,
            rightCut: 3294,
            leftWeld: 2042,
            rightWeld: 3342,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2006-01',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3297,
            rightCut: 4687,
            leftWeld: 3442,
            rightWeld: 4742,
            item_qty: 1,
            lCuttingNumber: 4,
          },
          {
            id: 'GR2005-04',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1304,
            lep_mm: 52,
            rep_mm: 52,
            leftCut: 4690,
            rightCut: 5994,
            leftWeld: 4842,
            rightWeld: 5942,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 12,
        qty: 1,
        gratings: 5,
        loss: 58.2,
        gratings_data: [
          {
            id: 'GR2006-08',
            option: 0,
            width_mm: 905,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2005-08',
            option: 0,
            width_mm: 845,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 1990,
            leftWeld: 1050,
            rightWeld: 1950,
            item_qty: 1,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2002-03',
            option: 0,
            width_mm: 755,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1290,
            lep_mm: 95,
            rep_mm: 95,
            leftCut: 1990,
            rightCut: 3280,
            leftWeld: 2085,
            rightWeld: 3185,
            item_qty: 1,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2006-09',
            option: 0,
            width_mm: 755,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 3280,
            rightCut: 4670,
            leftWeld: 3325,
            rightWeld: 4625,
            item_qty: 1,
            lCuttingNumber: 4,
          },
          {
            id: 'GR2006-02',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4670,
            rightCut: 6060,
            leftWeld: 4715,
            rightWeld: 6015,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 13,
        qty: 1,
        gratings: 5,
        loss: 62.9,
        gratings_data: [
          {
            id: 'GR2004-11',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1210,
            leftWeld: 70,
            rightWeld: 1170,
            item_qty: 3,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-05',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1080,
            lep_mm: 90,
            rep_mm: 90,
            leftCut: 3570,
            rightCut: 4650,
            leftWeld: 3660,
            rightWeld: 4560,
            item_qty: 1,
            lCuttingNumber: 4,
          },
          {
            id: 'GR2006-10',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4650,
            rightCut: 6040,
            leftWeld: 4695,
            rightWeld: 5995,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 14,
        qty: 1,
        gratings: 5,
        loss: 62.9,
        gratings_data: [
          {
            id: 'GR2004-15',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1210,
            leftWeld: 70,
            rightWeld: 1170,
            item_qty: 3,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-09',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1080,
            lep_mm: 90,
            rep_mm: 90,
            leftCut: 3570,
            rightCut: 4650,
            leftWeld: 3660,
            rightWeld: 4560,
            item_qty: 1,
            lCuttingNumber: 4,
          },
          {
            id: 'GR2006-11',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 4650,
            rightCut: 6040,
            leftWeld: 4695,
            rightWeld: 5995,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 15,
        qty: 1,
        gratings: 5,
        loss: 61.1,
        gratings_data: [
          {
            id: 'GR2004-17',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1210,
            leftWeld: 70,
            rightWeld: 1170,
            item_qty: 4,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2002-03',
            option: 0,
            width_mm: 755,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1290,
            lep_mm: 95,
            rep_mm: 95,
            leftCut: 4750,
            rightCut: 6040,
            leftWeld: 4845,
            rightWeld: 5945,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 16,
        qty: 1,
        gratings: 5,
        loss: 72.4,
        gratings_data: [
          {
            id: 'GR2002-14',
            option: 0,
            width_mm: 815,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2004-35',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 2190,
            leftWeld: 1050,
            rightWeld: 2150,
            item_qty: 1,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2006-06',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1180,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 2190,
            rightCut: 3370,
            leftWeld: 2230,
            rightWeld: 3330,
            item_qty: 2,
            lCuttingNumber: 3,
          },
          {
            id: 'GR2002-04',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1290,
            lep_mm: 95,
            rep_mm: 95,
            leftCut: 4550,
            rightCut: 5840,
            leftWeld: 4645,
            rightWeld: 5745,
            item_qty: 1,
            lCuttingNumber: 5,
          },
        ],
      },
      {
        panelNumber: 17,
        qty: 1,
        gratings: 5,
        loss: 98.1,
        gratings_data: [
          {
            id: 'GR2004-23',
            option: 0,
            width_mm: 785,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2002-11',
            option: 0,
            width_mm: 755,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 1990,
            leftWeld: 1050,
            rightWeld: 1950,
            item_qty: 2,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2004-01',
            option: 0,
            width_mm: 545,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 1390,
            lep_mm: 45,
            rep_mm: 45,
            leftCut: 2970,
            rightCut: 4360,
            leftWeld: 3015,
            rightWeld: 4315,
            item_qty: 2,
            lCuttingNumber: 4,
          },
        ],
      },
      {
        panelNumber: 18,
        qty: 1,
        gratings: 6,
        loss: 100.0,
        gratings_data: [
          {
            id: 'GR2002-17',
            option: 0,
            width_mm: 725,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 1,
            lCuttingNumber: 1,
          },
          {
            id: 'GR2002-09',
            option: 0,
            width_mm: 695,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1010,
            rightCut: 1990,
            leftWeld: 1050,
            rightWeld: 1950,
            item_qty: 1,
            lCuttingNumber: 2,
          },
          {
            id: 'GR2002-05',
            option: 0,
            width_mm: 605,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 1990,
            rightCut: 2970,
            leftWeld: 2030,
            rightWeld: 2930,
            item_qty: 4,
            lCuttingNumber: 3,
          },
        ],
      },
      {
        panelNumber: 19,
        qty: 1,
        gratings: 2,
        loss: 182.2,
        gratings_data: [
          {
            id: 'GR2004-04',
            option: 0,
            width_mm: 515,
            orderNumber: 'GR20002-4-5-6',
            customerCode: 'KC코트렐',
            drawingNumber: 'P01',
            length_mm: 980,
            lep_mm: 40,
            rep_mm: 40,
            leftCut: 30,
            rightCut: 1010,
            leftWeld: 70,
            rightWeld: 970,
            item_qty: 2,
            lCuttingNumber: 1,
          },
        ],
      },
    ],
  },
};
export default CuttingPlan;
